@CMP-3 @AutoGenerated
Feature: User login via email and password

  Scenario: Successful login with valid email and password
    Given user is on the login page
    When user enters a valid email "user@example.com" and password "password123"
    Then user is redirected to the dashboard
    And a session token is stored in cookies

  Scenario: Login with invalid email format
    Given user is on the login page
    When user enters an invalid email "userexample.com" and password "password123"
    Then an error message "Please enter a valid email address" is displayed

  Scenario: Login with invalid password
    Given user is on the login page
    When user enters a valid email "user@example.com" and an invalid password "pass"
    Then an error message "Password must be at least 8 characters long and include numbers" is displayed

  Scenario: Login attempt with a locked account
    Given user is on the login page
    When user enters credentials for a locked account "locked@example.com" and "locked123"
    Then an error message "Your account is locked" is displayed

  Scenario: Login with empty email and password fields
    Given user is on the login page
    When user tries to login with empty email and password fields
    Then an error message "Email and password fields cannot be empty" is displayed