@SCRUM-2 @AutoGenerated
Feature: Refund Request from Order Details

  Scenario: Request a refund for an eligible order
    Given the customer is logged in and views an eligible order
    When the customer selects a refund reason and requests a refund
    Then the order status should update to "Refund Requested"
    And a confirmation email should be sent to the customer
    And an analytics event for "Refund Request Initiated" should be recorded

  Scenario: Attempt to request a refund for an ineligible order
    Given the customer is logged in and views an ineligible order
    When the customer attempts to request a refund
    Then the refund option should not be visible
    And no refund request should be processed

  Scenario: Request a refund without selecting a reason
    Given the customer is logged in and views an eligible order
    When the customer attempts to request a refund without selecting a reason
    Then the refund request should not be processed
    And an error message "Please select a refund reason" should be displayed