@CMP-5 @AutoGenerated
Feature: Enhance user profile editing

  Scenario: Successfully update display name and bio
    Given the user is logged in and on the Profile Settings page
    When the user updates the display name to "NewDisplayName"
    And the user updates the bio to "NewBio"
    And the user saves the profile changes
    Then the profile should display the updated display name "NewDisplayName"
    And the profile should display the updated bio "NewBio"

  Scenario: Successfully upload a valid avatar image
    Given the user is logged in and on the Profile Settings page
    When the user uploads a valid avatar image "valid_avatar.jpg"
    Then the new avatar should be displayed on the profile page

  Scenario: Attempt to upload an invalid file type as avatar
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "invalid_file.txt"
    Then an error message "Invalid file type. Please upload an image file." should be displayed

  Scenario: Attempt to upload an image exceeding the size limit
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "large_image.jpg"
    Then an error message "File size exceeds the 5 MB limit." should be displayed

  Scenario: Attempt to upload an image below the minimum dimension requirements
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "small_image.jpg"
    Then an error message "Image dimensions are too small. Minimum size is 128x128 pixels." should be displayed

  Scenario: Display default avatar if no avatar is uploaded
    Given the user is logged in and on the Profile Settings page
    And the user does not upload a new avatar
    When the user views the profile page
    Then the default avatar should be displayed