@CMP-5 @AutoGenerated
Feature: User Profile Editing

  Scenario: Successfully update display name and bio
    Given the user is logged in and on the Profile Settings page
    When the user updates the display name to "John Doe"
    And the user updates the bio to "Just a regular John"
    And the user clicks the save profile button
    Then the profile should be updated with display name "John Doe"
    And the profile should be updated with bio "Just a regular John"

  Scenario: Successfully upload a valid avatar image
    Given the user is logged in and on the Profile Settings page
    When the user uploads a valid avatar image "avatar.jpg"
    And the user clicks the save profile button
    Then the new avatar should be displayed on the profile page

  Scenario: Attempt to upload an invalid file type as avatar
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "avatar.gif"
    Then an error message "Invalid file type. Only JPG and PNG are allowed." should be displayed

  Scenario: Attempt to upload an avatar image exceeding file size limit
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "large_avatar.png"
    Then an error message "File size exceeds the 5 MB limit." should be displayed

  Scenario: Attempt to upload an avatar image with too small dimensions
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload a file "small_avatar.jpg"
    Then an error message "Image dimensions are too small. Minimum size is 128x128 pixels." should be displayed