@CMP-5 @AutoGenerated
Feature: Enhance User Profile Editing

  Scenario: Successfully update display name and bio with avatar upload
    Given the user is logged in and on the Profile Settings page
    When the user updates the display name to "New Name"
    And the user updates the bio to "New Bio"
    And the user uploads a valid avatar image "valid_avatar.jpg"
    And the user saves the profile changes
    Then the profile should display the updated display name "New Name"
    And the profile should display the updated bio "New Bio"
    And the new avatar should be visible on the profile page

  Scenario: Attempt to upload an avatar with an invalid file type
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload an avatar with file "invalid_avatar.gif"
    Then an error message "Invalid file type. Only JPG and PNG are allowed." should be displayed

  Scenario: Attempt to upload an avatar exceeding the file size limit
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload an avatar with file "large_avatar.png"
    Then an error message "File size exceeds the 5 MB limit." should be displayed

  Scenario: Attempt to upload an avatar below the minimum dimension requirements
    Given the user is logged in and on the Profile Settings page
    When the user attempts to upload an avatar with file "small_avatar.jpg"
    Then an error message "Image dimensions are too small. Minimum size is 128x128 pixels." should be displayed

  Scenario: Display default avatar when no avatar is uploaded
    Given the user is logged in and on the Profile Settings page
    And the user updates the display name to "Another Name"
    And the user updates the bio to "Another Bio"
    And the user does not upload a new avatar
    And the user saves the profile changes
    Then the profile should display the default avatar image