@SCRUNM-3 @AutoGenerated
Feature: Jira API test environment configuration
  As a tester, I want to set up and validate the Jira REST API connection for test automation.

  Scenario: Create API token and configure authentication
    Given API token is created with valid credentials
    When API token is configured for authentication
    Then API token is verified for read/write operations

  Scenario: Test fetching a single ticket from the sprint
    Given API token is authenticated
    When API token fetches a single ticket from the sprint
    Then API token verifies the fetched ticket details

  Scenario: Test fetching multiple tickets from the sprint
    Given API token is authenticated
    When API token fetches multiple tickets from the sprint
    Then API token verifies the fetched ticket details

  Scenario: Verify access permissions for read/write operations
    Given API token is authenticated
    When API token attempts to perform read/write operations
    Then API token verifies access permissions for read/write operations

  Scenario: Document sample API requests and responses
    Given API token is authenticated
    When API token documents sample API requests and responses
    Then API token verifies the documented API requests and responses