@SCRUM-5 @AutoGenerated
Feature: User login
  As a user, I want to be able to log in with valid credentials and have the login button disabled after first click until response arrives.

Scenario: Successful login with multiple clicks
  Given user is on login page
  When user enters valid credentials and clicks login button multiple times quickly
  Then login button should be disabled after first click until response arrives

Scenario: Failed login with invalid credentials
  Given user is on login page
  When user enters invalid credentials and clicks login button
  Then error message should appear indicating incorrect credentials