@SCRAM-7 @AutoGenerated
Feature: Add to cart functionality from product search results
  As a customer, I want to search for a product and add it to my cart directly from the search results page so that I can quickly make purchases.

Scenario: Search for a specific product and add to cart
    Given user is on Amazon homepage
    When user searches for "wireless mouse"
    Then user sees search results with wireless mice
    And user can add product to cart from search results page

Scenario: Add multiple products to cart
    Given user is on Amazon homepage
    When user searches for "wireless mouse" and "laptop"
    Then user sees search results with wireless mice and laptops
    And user can add both products to cart from search results page

Scenario: Update cart after adding product
    Given user is on Amazon homepage
    When user searches for "wireless mouse" and adds it to cart
    Then cart updates with the selected item